# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56661cca1b7a9ea59ebb1175f6526586d59f2cf55ade6f69129f9f44def9abb83ead1724c3652760efe41ce38547baf09bb312c04eebc6b7cd454a475170917a

test:
  secret_key_base: bf5ed4e50cfd92cd3c04a566ea35642a94d500f04bd83bb87691daf46c80d73f6611615a863ed6dfb383279fd064d7726057601b17f7480e5e90eceeea845a51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
